version: '2'

services:
  mymaster:
    image: gettyimages/spark:latest
    command: bin/spark-class org.apache.spark.deploy.master.Master -h mymaster
    hostname: mymaster
    container_name: mymaster
    environment:
      - MASTER=spark://mymaster:7077
      - SPARK_CONF_DIR=/conf
      - SPARK_PUBLIC_DNS=localhost
    expose:
      - 6066
      - 7001
      - 7002
      - 7003
      - 7004
      - 7005
      - 7006
      - 7077
    ports:
      - 4040:4040
      - 6066:6066
      - 7077:7077
      - 8080:8080
    volumes:
      - ./conf/sparkmaster:/conf
      - $DATA_ROOT:/tmp/data
      - ./target/scala-2.11:/app

  myworker:
    image: gettyimages/spark:latest
    command: bin/spark-class org.apache.spark.deploy.worker.Worker spark://mymaster:7077
    hostname: myworker
    container_name: myworker
    environment:
      SPARK_CONF_DIR: /conf
      SPARK_WORKER_CORES: 2
      SPARK_WORKER_MEMORY: 4g
      SPARK_WORKER_PORT: 8881
      SPARK_WORKER_WEBUI_PORT: 8081
      SPARK_PUBLIC_DNS: localhost
    depends_on:
      - mymaster
    expose:
      - 7012
      - 7013
      - 7014
      - 7015
      - 7016
      - 8081
      - 8881
    ports:
      - 8081:8081
    volumes:
      - ./conf/sparkworker:/conf
      - $DATA_ROOT:/tmp/data